// generate-config.js
// Generates config.js dynamically from environment variables (GitHub Secrets or Vercel Environment Variables).

const fs = require('fs');

const url = process.env.APPS_SCRIPT_URL || '';
const secret = process.env.APPS_SCRIPT_SECRET || '';

// If config.js already exists and environment variables are not supplied (e.g., local dev), retain existing config.js
if (fs.existsSync('config.js') && !url && !secret) {
  console.log('[generate-config] Preserving existing local config.js.');
  process.exit(0);
}

const fileContent = `// Auto-generated by build / deployment pipeline
// Generated from environment variables (GitHub Secrets / Vercel Environment Variables)

export const APPS_SCRIPT_URL = ${JSON.stringify(url)};
export const APPS_SCRIPT_SECRET = ${JSON.stringify(secret)};
`;

try {
  fs.writeFileSync('config.js', fileContent, 'utf8');
  console.log('[generate-config] Successfully generated config.js.');
} catch (err) {
  console.error('[generate-config] Failed to write config.js:', err);
  process.exit(1);
}
